import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    'nav.login': 'Login',
    'nav.getStarted': 'Get Started',
    'banner.exclusive': 'TOROCON EXCLUSIVE: Get Elite Package for $129/month (Save $370/month!)',
    'hero.title': 'Transform Your Tax Business Into a Year-Round Success',
    'hero.description': 'Master cash flow, sales systems, marketing, and leadership through 12 power-packed workshops designed specifically for Toro Tax franchise owners.',
    'hero.cta1': 'View Special Offer',
    'hero.cta2': 'View Courses',
    'stats.courses': 'Courses',
    'stats.hours': 'Hours of Content',
    'stats.owners': 'of Successful Owners',
    'stats.retention': 'Client Retention Rate',
    'stats.support': 'Priority Support',
    'modal.exclusive': 'TOROCON EXCLUSIVE OFFER',
    'modal.title': 'Get Elite Access for Only $129/month',
    'modal.subtitle': 'Pay $299 registration + $129/month and get the full $499/month Elite Package',
    'modal.features': 'All Elite Features Included!',
    'modal.feature1': '12 workshop courses (24 hours) - LIFETIME ACCESS',
    'modal.feature2': '12 Town Hall sessions',
    'modal.feature3': 'Complete video library',
    'modal.feature4': 'Podcast library (EN & ES)',
    'modal.feature5': 'Weekly tips & best practices',
    'modal.feature6': 'Business Analysis ($9,995 value)',
    'modal.feature7': 'Priority support & coaching',
    'modal.feature8': 'Private community access',
    'modal.totalValue': 'TOTAL VALUE',
    'modal.valueAmount': '$16,000+',
    'modal.valueDesc': 'Includes $9,995 Business Analysis + LIFETIME ACCESS',
    'modal.cta': 'Claim This Offer Now',
    'promo.exclusive': 'TOROCON EXCLUSIVE OFFER',
    'promo.title': 'Get Elite Access for Only $129/month',
    'promo.subtitle': 'Pay $299 registration + $129/month and get the full',
    'promo.elitePackage': '$499/month Elite Package',
    'promo.regularPrice': 'Regular Price',
    'promo.perMonth': 'per month',
    'promo.promoPrice': 'Promo Price',
    'promo.youSave': 'You Save',
    'promo.everyMonth': 'every month!',
    'promo.whatsIncluded': "What's Included:",
    'promo.included1': 'All 12 workshop courses (24 hours) - LIFETIME ACCESS',
    'promo.included2': '12 Town Hall sessions',
    'promo.included3': 'Complete video library',
    'promo.included4': 'Full podcast library',
    'promo.included5': 'Weekly tips & resources',
    'promo.included6': 'Business Analysis ($9,995 value)',
    'promo.included7': 'Priority support & coaching',
    'promo.included8': 'Private community access',
    'promo.cta': 'View Full Details & Sign Up',
    'promo.totalValue': '$16,000+ Total Value | Includes LIFETIME ACCESS',
    'journey.title': 'Your Learning Journey',
    'journey.subtitle': 'A Structured Path to Mastery',
    'journey.step1': 'Foundation',
    'journey.step1desc': 'Weeks 1-2',
    'journey.step2': 'Growth',
    'journey.step2desc': 'Weeks 3-5',
    'journey.step3': 'Optimization',
    'journey.step3desc': 'Weeks 6-8',
    'journey.step4': 'Leadership',
    'journey.step4desc': 'Weeks 9-10',
    'journey.step5': 'Mastery',
    'journey.step5desc': 'Weeks 11-12',
    'courses.title': '12 Powerful Courses',
    'courses.subtitle': 'Each course is 120 minutes of intensive, practical training',
    'courses.course1': 'Mastering Cashflow & Profitability',
    'courses.course2': 'Financial Literacy for Franchise Owners',
    'courses.course3': 'Building High-Performance Sales Systems',
    'courses.course4': 'Marketing Strategies for Year-Round Success',
    'courses.course5': 'Digital Marketing & Social Media Mastery',
    'courses.course6': 'Customer Experience & Retention',
    'courses.course7': 'Building & Managing Teams',
    'courses.course8': 'Operational Excellence',
    'courses.course9': 'Tax Season Preparation & Execution',
    'courses.course10': 'Off-Season Business Development',
    'courses.course11': 'Leadership Skills for Franchise Owners',
    'courses.course12': 'Employee Engagement & Retention',
    'courses.duration': '120 min',
    'testimonials.title': 'Join Hundreds of Successful Franchise Owners',
    'testimonials.subtitle': 'See what our members are saying',
    'testimonials.rating': 'Trusted by hundreds of franchise owners • 4.9/5 rating • 98% would recommend',
    'pricing.title': 'Choose Your Plan',
    'pricing.subtitle': 'All plans include lifetime access to course materials',
    'pricing.promo': 'PROMO',
    'pricing.elite': 'Elite',
    'pricing.essentials': 'Essentials',
    'pricing.promoDesc': 'Limited time offer',
    'pricing.eliteDesc': 'Full access to everything',
    'pricing.essentialsDesc': 'Core courses only',
    'pricing.perMonth': '/month',
    'pricing.registration': '+ $299 registration',
    'pricing.selectPlan': 'Select This Plan',
    'pricing.viewFullPricing': 'View Full Pricing Details & Comparison',
    'pricing.allPlans': 'All plans include per-office access',
    'cta.final': 'Get Started Today',
    'footer.delivered': 'Delivered by Peak Performance Partners',
    'footer.rights': 'All Rights Reserved',
  },
  es: {
    'nav.login': 'Iniciar Sesión',
    'nav.getStarted': 'Comenzar',
    'banner.exclusive': 'EXCLUSIVO TOROCON: Obtenga el Paquete Elite por $129/mes (¡Ahorre $370/mes!)',
    'hero.title': 'Transforme Su Negocio de Impuestos en un Éxito Durante Todo el Año',
    'hero.description': 'Domine el flujo de efectivo, sistemas de ventas, marketing y liderazgo a través de 12 talleres poderosos diseñados específicamente para propietarios de franquicias Toro Tax.',
    'hero.cta1': 'Ver Oferta Especial',
    'hero.cta2': 'Ver Cursos',
    'stats.courses': 'Cursos',
    'stats.hours': 'Horas de Contenido',
    'stats.owners': 'de Propietarios Exitosos',
    'stats.retention': 'Tasa de Retención',
    'stats.support': 'Soporte Prioritario',
    'modal.exclusive': 'OFERTA EXCLUSIVA DE TOROCON',
    'modal.title': 'Obtenga Acceso Elite por Solo $129/mes',
    'modal.subtitle': 'Pague $299 de registro + $129/mes y obtenga el Paquete Elite completo de $499/mes',
    'modal.features': '¡Todas las Características Elite Incluidas!',
    'modal.feature1': '12 cursos taller (24 horas) - ACCESO DE POR VIDA',
    'modal.feature2': '12 sesiones de Town Hall',
    'modal.feature3': 'Biblioteca completa de videos',
    'modal.feature4': 'Biblioteca de podcasts (EN y ES)',
    'modal.feature5': 'Consejos semanales y mejores prácticas',
    'modal.feature6': 'Análisis de Negocio (valor de $9,995)',
    'modal.feature7': 'Soporte prioritario y coaching',
    'modal.feature8': 'Acceso a comunidad privada',
    'modal.totalValue': 'VALOR TOTAL',
    'modal.valueAmount': '$16,000+',
    'modal.valueDesc': 'Incluye Análisis de Negocio de $9,995 + ACCESO DE POR VIDA',
    'modal.cta': 'Reclamar Esta Oferta Ahora',
    'promo.exclusive': 'OFERTA EXCLUSIVA DE TOROCON',
    'promo.title': 'Obtenga Acceso Elite por Solo $129/mes',
    'promo.subtitle': 'Pague $299 de registro + $129/mes y obtenga el',
    'promo.elitePackage': 'Paquete Elite completo de $499/mes',
    'promo.regularPrice': 'Precio Regular',
    'promo.perMonth': 'por mes',
    'promo.promoPrice': 'Precio Promocional',
    'promo.youSave': 'Usted Ahorra',
    'promo.everyMonth': '¡cada mes!',
    'promo.whatsIncluded': 'Qué Está Incluido:',
    'promo.included1': 'Los 12 cursos taller (24 horas) - ACCESO DE POR VIDA',
    'promo.included2': '12 sesiones de Town Hall',
    'promo.included3': 'Biblioteca completa de videos',
    'promo.included4': 'Biblioteca completa de podcasts',
    'promo.included5': 'Consejos semanales y recursos',
    'promo.included6': 'Análisis de Negocio (valor de $9,995)',
    'promo.included7': 'Soporte prioritario y coaching',
    'promo.included8': 'Acceso a comunidad privada',
    'promo.cta': 'Ver Detalles Completos e Inscribirse',
    'promo.totalValue': 'Valor Total de $16,000+ | Incluye ACCESO DE POR VIDA',
    'journey.title': 'Su Viaje de Aprendizaje',
    'journey.subtitle': 'Un Camino Estructurado hacia la Maestría',
    'journey.step1': 'Fundación',
    'journey.step1desc': 'Semanas 1-2',
    'journey.step2': 'Crecimiento',
    'journey.step2desc': 'Semanas 3-5',
    'journey.step3': 'Optimización',
    'journey.step3desc': 'Semanas 6-8',
    'journey.step4': 'Liderazgo',
    'journey.step4desc': 'Semanas 9-10',
    'journey.step5': 'Maestría',
    'journey.step5desc': 'Semanas 11-12',
    'courses.title': '12 Cursos Poderosos',
    'courses.subtitle': 'Cada curso es de 120 minutos de entrenamiento intensivo y práctico',
    'courses.course1': 'Dominando el Flujo de Efectivo y Rentabilidad',
    'courses.course2': 'Educación Financiera para Propietarios de Franquicias',
    'courses.course3': 'Construyendo Sistemas de Ventas de Alto Rendimiento',
    'courses.course4': 'Estrategias de Marketing para Éxito Todo el Año',
    'courses.course5': 'Dominio del Marketing Digital y Redes Sociales',
    'courses.course6': 'Experiencia del Cliente y Retención',
    'courses.course7': 'Construyendo y Gestionando Equipos',
    'courses.course8': 'Excelencia Operacional',
    'courses.course9': 'Preparación y Ejecución de Temporada de Impuestos',
    'courses.course10': 'Desarrollo de Negocio Fuera de Temporada',
    'courses.course11': 'Habilidades de Liderazgo para Propietarios de Franquicias',
    'courses.course12': 'Compromiso y Retención de Empleados',
    'courses.duration': '120 min',
    'testimonials.title': 'Únase a Cientos de Propietarios de Franquicias Exitosos',
    'testimonials.subtitle': 'Vea lo que dicen nuestros miembros',
    'testimonials.rating': 'Confiado por cientos de propietarios de franquicias • Calificación 4.9/5 • 98% lo recomendaría',
    'pricing.title': 'Elija Su Plan',
    'pricing.subtitle': 'Todos los planes incluyen acceso de por vida a los materiales del curso',
    'pricing.promo': 'PROMO',
    'pricing.elite': 'Elite',
    'pricing.essentials': 'Esenciales',
    'pricing.promoDesc': 'Oferta por tiempo limitado',
    'pricing.eliteDesc': 'Acceso completo a todo',
    'pricing.essentialsDesc': 'Solo cursos principales',
    'pricing.perMonth': '/mes',
    'pricing.registration': '+ $299 registro',
    'pricing.selectPlan': 'Seleccionar Este Plan',
    'pricing.viewFullPricing': 'Ver Detalles Completos de Precios y Comparación',
    'pricing.allPlans': 'Todos los planes incluyen acceso por oficina',
    'cta.final': 'Comenzar Hoy',
    'footer.delivered': 'Entregado por Peak Performance Partners',
    'footer.rights': 'Todos los Derechos Reservados',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
